-- MySQL Script generated by MySQL Workbench
-- Tue Dec 13 22:08:21 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema ie04t2022c
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `ie04t2022c` ;

-- -----------------------------------------------------
-- Schema ie04t2022c
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ie04t2022c` DEFAULT CHARACTER SET utf8 ;
USE `ie04t2022c` ;

-- -----------------------------------------------------
-- Table `ie04t2022c`.`account`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ie04t2022c`.`account` ;

CREATE TABLE IF NOT EXISTS `ie04t2022c`.`account` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `authority_id` BIGINT UNSIGNED NOT NULL,
  `username` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `deleted` TINYINT NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  UNIQUE INDEX `username_UNIQUE` (`username` ASC) VISIBLE,
  CONSTRAINT `ibfk_account_authority_id_authorities_id`
    FOREIGN KEY (`authority_id`)
    REFERENCES `ie04t2022c`.`authority` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `ie04t2022c`.`assistance_type`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ie04t2022c`.`assistance_type` ;

CREATE TABLE IF NOT EXISTS `ie04t2022c`.`assistance_type` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `hourly_pay` BIGINT UNSIGNED NOT NULL,
  `deleted` TINYINT NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `ie04t2022c`.`assistant`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ie04t2022c`.`assistant` ;

CREATE TABLE IF NOT EXISTS `ie04t2022c`.`assistant` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `user_id` BIGINT UNSIGNED NOT NULL,
  `assistant_nationality_id` BIGINT UNSIGNED NOT NULL,
  `assistant_graduate_id` BIGINT UNSIGNED NOT NULL,
  `student_year` INT UNSIGNED NOT NULL,
  `student_id` VARCHAR(45) NOT NULL,
  `deleted` TINYINT NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  UNIQUE INDEX `user_id_UNIQUE` (`user_id` ASC) VISIBLE,
  INDEX `ibfk_assistant_assistant_graduates_id_assistant_graduate_id_idx` (`assistant_graduate_id` ASC) VISIBLE,
  CONSTRAINT `ibfk_assistant_assistant_nationality_id_nationalities_id`
    FOREIGN KEY (`assistant_nationality_id`)
    REFERENCES `ie04t2022c`.`assistant_nationality` (`id`),
  CONSTRAINT `ibfk_assistant_user_id_users_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `ie04t2022c`.`user` (`id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT,
  CONSTRAINT `ibfk_assistant_assistant_graduates_id_assistant_graduate_id`
    FOREIGN KEY (`assistant_graduate_id`)
    REFERENCES `ie04t2022c`.`assistant_graduate` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `ie04t2022c`.`assistant_course`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ie04t2022c`.`assistant_course` ;

CREATE TABLE IF NOT EXISTS `ie04t2022c`.`assistant_course` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `assistant_id` BIGINT UNSIGNED NOT NULL,
  `course_id` BIGINT UNSIGNED NOT NULL,
  `deleted` TINYINT NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  CONSTRAINT `ibfk_assistant_course_assistant_id_assistants_id`
    FOREIGN KEY (`assistant_id`)
    REFERENCES `ie04t2022c`.`assistant` (`id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT,
  CONSTRAINT `ibfk_assistant_course_course_id_courses_id`
    FOREIGN KEY (`course_id`)
    REFERENCES `ie04t2022c`.`course` (`id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `ie04t2022c`.`assistant_graduate`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ie04t2022c`.`assistant_graduate` ;

CREATE TABLE IF NOT EXISTS `ie04t2022c`.`assistant_graduate` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `deleted` TINYINT NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `ie04t2022c`.`assistant_nationality`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ie04t2022c`.`assistant_nationality` ;

CREATE TABLE IF NOT EXISTS `ie04t2022c`.`assistant_nationality` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `weekly_work_hour_limit` TIME NOT NULL,
  `deleted` TINYINT NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `ie04t2022c`.`authority`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ie04t2022c`.`authority` ;

CREATE TABLE IF NOT EXISTS `ie04t2022c`.`authority` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `deleted` TINYINT NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `ie04t2022c`.`course`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ie04t2022c`.`course` ;

CREATE TABLE IF NOT EXISTS `ie04t2022c`.`course` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `coordinator_id` BIGINT UNSIGNED NOT NULL,
  `course_name_id` BIGINT UNSIGNED NOT NULL,
  `period_id` BIGINT UNSIGNED NOT NULL,
  `open_year` YEAR NOT NULL,
  `deleted` TINYINT NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `ibfk_cource_period_id_periods_id_idx` (`period_id` ASC) VISIBLE,
  INDEX `ibfk_course_course_name_id_course_name_id_idx` (`course_name_id` ASC) VISIBLE,
  CONSTRAINT `ibfk_course_coordinator_id_faculties_id`
    FOREIGN KEY (`coordinator_id`)
    REFERENCES `ie04t2022c`.`faculty` (`id`),
  CONSTRAINT `ibfk_course_period_id_periods_id`
    FOREIGN KEY (`period_id`)
    REFERENCES `ie04t2022c`.`period` (`id`),
  CONSTRAINT `ibfk_course_course_name_id_course_name_id`
    FOREIGN KEY (`course_name_id`)
    REFERENCES `ie04t2022c`.`course_name` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `ie04t2022c`.`course_name`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ie04t2022c`.`course_name` ;

CREATE TABLE IF NOT EXISTS `ie04t2022c`.`course_name` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `deleted` TINYINT NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ie04t2022c`.`faculty`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ie04t2022c`.`faculty` ;

CREATE TABLE IF NOT EXISTS `ie04t2022c`.`faculty` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `user_id` BIGINT UNSIGNED NOT NULL,
  `deleted` TINYINT NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  UNIQUE INDEX `user_id_UNIQUE` (`user_id` ASC) VISIBLE,
  CONSTRAINT `ibfk_faculty_user_id_users_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `ie04t2022c`.`user` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `ie04t2022c`.`faculty_course`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ie04t2022c`.`faculty_course` ;

CREATE TABLE IF NOT EXISTS `ie04t2022c`.`faculty_course` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `faculty_id` BIGINT UNSIGNED NOT NULL,
  `course_id` BIGINT UNSIGNED NOT NULL,
  `deleted` TINYINT NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  CONSTRAINT `ibfk_faculty_course_course_id_faculties_id`
    FOREIGN KEY (`faculty_id`)
    REFERENCES `ie04t2022c`.`faculty` (`id`),
  CONSTRAINT `ibfk_faculty_course_faculty_id_courses_id`
    FOREIGN KEY (`course_id`)
    REFERENCES `ie04t2022c`.`course` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `ie04t2022c`.`period`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ie04t2022c`.`period` ;

CREATE TABLE IF NOT EXISTS `ie04t2022c`.`period` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `term_id` BIGINT UNSIGNED NOT NULL,
  `period_from` DATE NOT NULL,
  `period_to` DATE NOT NULL,
  `deleted` TINYINT NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `ibfk_period_term_id_terms_id_idx` (`term_id` ASC) VISIBLE,
  CONSTRAINT `ibfk_period_term_id_terms_id`
    FOREIGN KEY (`term_id`)
    REFERENCES `ie04t2022c`.`term` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `ie04t2022c`.`record`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ie04t2022c`.`record` ;

CREATE TABLE IF NOT EXISTS `ie04t2022c`.`record` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `report_id` BIGINT UNSIGNED NOT NULL,
  `work_category_id` BIGINT UNSIGNED NOT NULL,
  `target_date` DATE NOT NULL,
  `start_time` TIME NULL DEFAULT NULL,
  `end_time` TIME NULL DEFAULT NULL,
  `break_time` TIME NULL DEFAULT NULL,
  `total_time` TIME NOT NULL DEFAULT '00:00:00',
  `deleted` TINYINT NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  CONSTRAINT `ibfk_record_report_id_reports_id`
    FOREIGN KEY (`report_id`)
    REFERENCES `ie04t2022c`.`report` (`id`),
  CONSTRAINT `ibfk_record_work_category_id_work_categories_id`
    FOREIGN KEY (`work_category_id`)
    REFERENCES `ie04t2022c`.`work_category` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `ie04t2022c`.`report`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ie04t2022c`.`report` ;

CREATE TABLE IF NOT EXISTS `ie04t2022c`.`report` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `assistant_course_id` BIGINT UNSIGNED NOT NULL,
  `assistance_type_id` BIGINT UNSIGNED NOT NULL,
  `target_year` YEAR NOT NULL,
  `target_month` DATE NOT NULL,
  `monthly_total_work_hour` TIME NOT NULL DEFAULT '0',
  `monthly_total_allocated_hour` TIME NULL DEFAULT NULL,
  `verified` TINYINT NOT NULL,
  `verified_staff_id` BIGINT UNSIGNED NULL,
  `verified_date` DATE NULL DEFAULT NULL,
  `approved` TINYINT NOT NULL,
  `approved_faculty_id` BIGINT UNSIGNED NULL,
  `approved_date` DATE NULL DEFAULT NULL,
  `edited_user_id` BIGINT UNSIGNED NOT NULL,
  `edited_date` DATE NULL DEFAULT NULL,
  `deleted` TINYINT NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `ibfk_report_assistant_types_id_assistant_type_id_idx` (`assistance_type_id` ASC) VISIBLE,
  CONSTRAINT `ibfk_report_approved_faculty_id_faculties_id`
    FOREIGN KEY (`approved_faculty_id`)
    REFERENCES `ie04t2022c`.`faculty` (`id`),
  CONSTRAINT `ibfk_report_assistant_course_id_assistant_courses_id`
    FOREIGN KEY (`assistant_course_id`)
    REFERENCES `ie04t2022c`.`assistant_course` (`id`),
  CONSTRAINT `ibfk_report_edited_user_id_users_id`
    FOREIGN KEY (`edited_user_id`)
    REFERENCES `ie04t2022c`.`user` (`id`),
  CONSTRAINT `ibfk_report_verified_staff_id_staffs_id`
    FOREIGN KEY (`verified_staff_id`)
    REFERENCES `ie04t2022c`.`staff` (`id`),
  CONSTRAINT `ibfk_report_assistance_type_id_assistance_types_id`
    FOREIGN KEY (`assistance_type_id`)
    REFERENCES `ie04t2022c`.`assistance_type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `ie04t2022c`.`staff`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ie04t2022c`.`staff` ;

CREATE TABLE IF NOT EXISTS `ie04t2022c`.`staff` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `user_id` BIGINT UNSIGNED NOT NULL,
  `deleted` TINYINT NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  UNIQUE INDEX `user_id_UNIQUE` (`user_id` ASC) VISIBLE,
  CONSTRAINT `ibfk_staff_user_id_users_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `ie04t2022c`.`user` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `ie04t2022c`.`term`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ie04t2022c`.`term` ;

CREATE TABLE IF NOT EXISTS `ie04t2022c`.`term` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `deleted` TINYINT NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `ie04t2022c`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ie04t2022c`.`user` ;

CREATE TABLE IF NOT EXISTS `ie04t2022c`.`user` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `account_id` BIGINT UNSIGNED NOT NULL,
  `first_name` VARCHAR(45) NOT NULL,
  `middle_name` VARCHAR(45) NULL DEFAULT NULL,
  `last_name` VARCHAR(45) NOT NULL,
  `start_date` DATETIME NOT NULL,
  `deleted` TINYINT NOT NULL DEFAULT '0',
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  UNIQUE INDEX `account_id_UNIQUE` (`account_id` ASC) VISIBLE,
  CONSTRAINT `ibfk_user_account_id_accounts_id`
    FOREIGN KEY (`account_id`)
    REFERENCES `ie04t2022c`.`account` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `ie04t2022c`.`work_category`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ie04t2022c`.`work_category` ;

CREATE TABLE IF NOT EXISTS `ie04t2022c`.`work_category` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `deleted` TINYINT NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
